### ISSUE TITLE
装好了tex，插件报错Cannot run program "xelatex" (in directory "~/mirai/./temp/lx1627895398887\"): error=2, No such file or directory

### ISSUE THREAD

**Issue by lwzhenglittle** [khjxiaogu/MiraiLatexPlugin#1]
如题，具体情况如图，系统为ubuntu，java情况图中有

![Latex安装证明](https://user-images.githubusercontent.com/25863941/127837667-b4a45feb-811e-4ebb-a3cc-45700d4f193e.png)
![JDK版本](https://user-images.githubusercontent.com/25863941/127837678-890fbcb1-fdcd-4655-b7dd-26da32e68ed1.png)
![具体错误](https://user-images.githubusercontent.com/25863941/127837683-93af8b66-b068-4355-b893-ce922255c9f2.png)

若有需要可继续提供相关信息

**Comment by khjxiaogu** [comment]
没有在linux系统上进行过测试，下个版本修复

**Comment by lwzhenglittle** [comment]
好的，感谢开发者的无私奉献！！！
